[project]
name = "python-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
[tool.poetry.dependencies]
python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "streamlit>=1.43.2",
]
